/*
* Copyright (c) 2006-2007 Nokia Corporation and/or its subsidiary(-ies). 
* All rights reserved.
* This component and the accompanying materials are made available
* under the terms of "Eclipse Public License v1.0"
* which accompanies this distribution, and is available
* at the URL "http://www.eclipse.org/legal/epl-v10.html".
*
* Initial Contributors:
* Nokia Corporation - initial contribution.
*
* Contributors:
*
* Description:  Processor object for running queued tasks
 *
*/
// Created by TraceCompiler 2.3.0
// DO NOT EDIT, CHANGES WILL BE LOST

#ifndef __THUMBNAILTASKPROCESSORTRACES_H__
#define __THUMBNAILTASKPROCESSORTRACES_H__

#define KOstTraceComponentID 0x102830ab

#define CTHUMBNAILTASKPROCESSOR_CONSTRUCTL 0x86019e
#define DUP1_CTHUMBNAILTASKPROCESSOR_CONSTRUCTL 0x86019f
#define DUP2_CTHUMBNAILTASKPROCESSOR_CONSTRUCTL 0x8601a0
#define DUP3_CTHUMBNAILTASKPROCESSOR_CONSTRUCTL 0x8601a1
#define CTHUMBNAILTASKPROCESSOR_CTHUMBNAILTASKPROCESSOR 0x8601a2
#define CTHUMBNAILTASKPROCESSOR_ADDTASKL 0x8601a3
#define CTHUMBNAILTASKPROCESSOR_REMOVETASK 0x8601a4
#define DUP1_CTHUMBNAILTASKPROCESSOR_REMOVETASK 0x8601a5
#define DUP2_CTHUMBNAILTASKPROCESSOR_REMOVETASK 0x8601a6
#define DUP3_CTHUMBNAILTASKPROCESSOR_REMOVETASK 0x8601a7
#define CTHUMBNAILTASKPROCESSOR_REMOVETASKS 0x8601a8
#define DUP1_CTHUMBNAILTASKPROCESSOR_REMOVETASKS 0x8601a9
#define DUP2_CTHUMBNAILTASKPROCESSOR_REMOVETASKS 0x8601aa
#define DUP3_CTHUMBNAILTASKPROCESSOR_REMOVETASKS 0x8601ab
#define DUP4_CTHUMBNAILTASKPROCESSOR_REMOVETASKS 0x8601ac
#define CTHUMBNAILTASKPROCESSOR_REMOVEALLTASKS 0x8601ad
#define DUP1_CTHUMBNAILTASKPROCESSOR_REMOVEALLTASKS 0x8601ae
#define DUP2_CTHUMBNAILTASKPROCESSOR_REMOVEALLTASKS 0x8601af
#define DUP3_CTHUMBNAILTASKPROCESSOR_REMOVEALLTASKS 0x8601b0
#define DUP4_CTHUMBNAILTASKPROCESSOR_REMOVEALLTASKS 0x8601b1
#define CTHUMBNAILTASKPROCESSOR_RUNL 0x8601b2
#define DUP1_CTHUMBNAILTASKPROCESSOR_RUNL 0x8601b3
#define DUP2_CTHUMBNAILTASKPROCESSOR_RUNL 0x8601b4
#define DUP3_CTHUMBNAILTASKPROCESSOR_RUNL 0x8601b5
#define DUP4_CTHUMBNAILTASKPROCESSOR_RUNL 0x8601b6
#define DUP5_CTHUMBNAILTASKPROCESSOR_RUNL 0x8601b7
#define CTHUMBNAILTASKPROCESSOR_RUNERROR 0x8601b8
#define CTHUMBNAILTASKPROCESSOR_TASKCOMPLETE 0x8601b9
#define DUP1_CTHUMBNAILTASKPROCESSOR_TASKCOMPLETE 0x8601ba
#define DUP2_CTHUMBNAILTASKPROCESSOR_TASKCOMPLETE 0x8601bb
#define CTHUMBNAILTASKPROCESSOR_PERIODICTIMERCALLBACK 0x8601bc
#define DUP1_CTHUMBNAILTASKPROCESSOR_PERIODICTIMERCALLBACK 0x8601bd
#define CTHUMBNAILTASKPROCESSOR_SETDAEMONASPROCESS 0x8601be


#endif

// End of file

